

services:
  next-app:
    container_name: institucional-react
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    restart: always
    ports:
      - 8997:3000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
