version: "3"

services:
  next-app:
    container_name: institucional-react
    build:
      context: .
      dockerfile: Dockerfile

#    environment:
#      ENV_VARIABLE: ${ENV_VARIABLE}
#      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment
    env_file:
      - .env.production
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
