import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Hero from "@/app/pages/hero/hero";
import Script from "next/script";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Equatorial",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = headers().get('x-nonce') as string|undefined
  return (
    <html lang="en">
      <Script src="http://drupal-institucional-drupal-dev.apps.ocpdrupal.equatorial.corp" strategy="afterInteractive" nonce={nonce}/>
      <Script src="https://drupal-institucional-drupal-dev.apps.ocpdrupal.equatorial.corp" strategy="afterInteractive" nonce={nonce}/>
      <body className={inter.className}>
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
  );
}
