import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Hero from "@/app/pages/hero/hero";
import PerguntasFrequentes from "@/app/pages/perguntasFrequentes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Equatorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Hero/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
